### PR TITLE
Adding popular algorihms in Go

### PR DESCRIPTION
**Pull request by BaseMax**
Algorithms:

- Binary Search Algorithm
- Breadth First Search (BFS) Algorithm
- Depth First Search (DFS) Algorithm
- Merge Sort Algorithm
- Quicksort Algorithm
- Kruskal’s Algorithm

Your friend,
Ali

### CODE REVIEW

**Review by jbampton — COMMENTED** [review]
Looks pretty good.  I did not test any of this.

One comment:

In Golang if you can determine the length upfront of a "structure" then you can `make` it first and use basic `assignment` instead of using `append`.

And using `make` is faster than always "appending".

https://stackoverflow.com/questions/38654729/golang-slice-append-vs-assign-performance

**Comment by BaseMax** [comment]
New algorithms:

- Floyd Warshall Algorithm
- Dijkstra’s Algorithm
- Bellman Ford Algorithm
- Kadane’s Algorithm
- Lee Algorithm
- Flood Fill Algorithm
- Floyd’s Cycle Detection Algorithm
- Union Find Algorithm
- Topological Sort Algorithm
- KMP Algorithm
- Insertion Sort Algorithm
- Selection Sort Algorithm
- Counting Sort Algorithm
- Heap Sort Algorithm
- Kahn’s Topological Sort Algorithm
- Huffman Coding Compression Algorithm
- Quickselect Algorithm
- Boyer–Moore Majority Vote Algorithm
- Euclid’s Algorithm

**Comment by BaseMax** [comment]
I only found an error:
```
C:\Users\Max\go-to-algorithms>go run "Floyd Cycle Detection.go"
Floyd’s Cycle Detection Algorithm
panic: runtime error: index out of range [10] with length 10

goroutine 1 [running]:
main.FloydCycleDetection(...)
```

**Comment by amarps** [comment]
hi @BaseMax i think it's best to use `snake_case` rather than using `Title Case With Space` for go file name  because it's simpler to type and every go file in golang source use it.
we can take a look at golang that source every go file use `snake_case` https://github.com/golang/go/tree/master/src

```bash
# snake_case
go run bellman_ford.go

# Title Case With Space
go run "Bellman Ford.go"
#or
go run Bellman\ Ford.go
```

**Comment by amarps** [comment]
do you planning to add all the algorithms in the root directory? i believe it will be easier to manage if you grouping algorithms in a folder by its usage.
for example
 ```bash
sorting:
    - quicksort.go
    - selectionsort.go
    - topologicalsort.go
searching:
    - binarysearch.go
    - breadfirstsearch.go
    - depthfirstsearch.go
....
 ```

**Comment by jbampton** [comment]
For sure you should never have `spaces` in filenames

**Comment by amarps** [comment]
currently for testing all the algorithms we need to run it one by one, waiting for one program to be done and execute another one.
like this
```
go run "Floyd Warshall.go"
go run "Dijkstra.go"
go run "Bellman Ford.go"
go run "Kadane.go"
go run "Lee.go"
go run "Flood Fill.go"
...
```

to make it simpler and maintanable we can use unit testing.
you can change current main function on each file to a test case.
so you will know which algorithms that runs as expected and which one had an error just in one command
```
go test -v ./...
```
you can read about unit testing here https://go.dev/doc/tutorial/add-a-test

**Comment by jbampton** [comment]
A long time ago I setup a Go test file.  Most likely can be better and does not have full coverage:

https://github.com/slurpcode/slurp/blob/main/scrapers/go/colly/github/main_test.go

**Comment by jbampton** [comment]
Would be nice to add testing to run with GitHub actions.  I did setup on Circle CI a long time ago before GitHub Actions came out.

https://github.com/slurpcode/slurp/blob/95dcf9672ef63ac7a61ae68d2d16437e154a7631/.circleci/config.yml#L189

Screen Shot 2022-10-29 at 1 37 19 pm

**Comment by BaseMax** [comment]
Hi friends, Thanks for the comments.
Feel free to change or add anything you want in the forked repository. So I can merge your PR, and finally we can merge this PR.

https://github.com/MaxFork/go-to-algorithms/

**Comment by BaseMax** [comment]
- amarps has been added as a collaborator with maintain permissions on the repository.
- jbampton has been added as a collaborator with maintain permissions on the repository.

**Review by jbampton — APPROVED** [review]
We are accepting this pull request.

The rest of the work from the review comments can be done later

**Pull request merged**
