### PR TITLE
feat: add new algorithm

### PR DESCRIPTION
**Pull request by sautmanurung1**
here I have added several algorithms in the golang programming language

### CODE REVIEW

**Comment by BaseMax** [comment]
Welcome.

**Comment by sautmanurung1** [comment]
Can this pull request be reviewed first?
@jbampton @BaseMax

**Review by wickedknock — APPROVED** [review]
All three looks good and working , maybe later change the palindrome function to accept an interface value to check for alpha numeric palindromes by converting it to a string

**Comment by sautmanurung1** [comment]
Okay sir, i will noted

**Comment by jbampton** [comment]
Thanks

**Pull request merged**
