### PR TITLE
refactor: fix filename and folder structure

### PR DESCRIPTION
**Pull request by amarps**
changes:
change filename from Title Case to snake_case
move file to folder by its usage

### CODE REVIEW

**Review by BaseMax — CHANGES_REQUESTED** [review]
Hi there, Thanks for your PR.
A question, If you only renamed the files. so why all lines have changed in the DIFF view of GitHub? In this way it's hard to review and check all lines.

**Comment by amarps** [comment]
i didn't change a single line on this PR just move and rename the file.
i think it's just how git behave when moving file
image

**Review by jbampton — CHANGES_REQUESTED** [review]
```
mruby % git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        renamed:    TODO.md -> TODO-temp.md

mruby % git diff
mruby % 
```

**Comment by amarps** [comment]
i use git bash for windows

**Comment by BaseMax** [comment]
Try it again. remove your fork repo or undo it and again fork from the main repository and only rename the files. without changnig anything.

Thank you in advance.

**Comment by amarps** [comment]
i can't. my local machine autmatically generate lots of diff when i rename or move a file. i use windows

**Comment by jbampton** [comment]
Use `git mv`

```
mruby % git mv TODO.md TODO-temp.md
mruby % git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        renamed:    TODO.md -> TODO-temp.md

mruby % git diff
mruby %
```

**Comment by jbampton** [comment]
https://git-scm.com/docs/git-mv

**Comment by BaseMax** [comment]
> i can't. my local machine autmatically generate lots of diff when i rename or move a file. i use windows

John, maybe it's related to ending lines? \n or \r\n ?

**Comment by BaseMax** [comment]
- https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
- https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Comment by amarps** [comment]
have used github for long time didn't know about `git mv` thank you will update the PR soon.

**Comment by amarps** [comment]
> > i can't. my local machine autmatically generate lots of diff when i rename or move a file. i use windows
> 
> John, maybe it's related to ending lines? \n or \r\n ?

i'm also thought it is what causing the long diff but after i try `git mv` the long diff is gone.

**Comment by jbampton** [comment]
Most editors can show line endings.  For example in `Atom`:

Screen Shot 2022-10-31 at 5 57 54 pm

**Comment by amarps** [comment]
yes on my vscode there is also showing line ending 
image

**Comment by jbampton** [comment]
When you setup Git on Windows there are settings:

git-line-endings

**Comment by jbampton** [comment]
A simple `cat -e <filename>` works just fine.

This displays Unix line endings (\n or LF) as $ and Windows line endings (\r\n or CRLF) as ^M$.

**Comment by jbampton** [comment]
@BaseMax the `secret sauce` really is:

```
go-to-algorithms % find . -name \*.go -exec grep -c $'\r' {} \;
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
go-to-algorithms % 
```

Shows a count of zero on all Go files.

I had to solve problems like this many times before on paid jobs in the past 🥇

**Comment by jbampton** [comment]
Last comment is updated

**Review by jbampton — APPROVED** [review]

**Pull request merged**
